name: "Run tests"
on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/test.yml'
      - 'flake.*'
      - 'hasql-effectful.cabal'
      - 'src/**/*'
      - 'pool-src/**/*'
      - 'test/**/*'
      - 'hie.yaml'
  push:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-20.04

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io https://cache.zw3rk.com https://cache.nixos.org/

    - run: nix run .#packages.x86_64-linux.hasql-pool-effectful-test
